[package]
name = "ac-esp"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_System_SystemServices",
    "Win32_UI_Input_KeyboardAndMouse",
]}

hudhook = "0.9"

imgui = "0.12"

anyhow = "1"